/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wonderly_util_NTServices */

#ifndef _Included_org_wonderly_util_NTServices
#define _Included_org_wonderly_util_NTServices
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wonderly_util_NTServices
 * Method:    logMessage
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wonderly_util_NTServices_logMessage
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_wonderly_util_NTServices
 * Method:    exit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_wonderly_util_NTServices_exit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
